
#  Equipo #1
#  Diaz Antonio Luis Pedro
#  6 de febrero de 2026


### Obtener busqueda
GET http://localhost:3000/api/motordebusqueda/busqueda?q=adidas

### Obtener filtro
GET http://localhost:3000/api/motordebusqueda/filtro?q=tenis&categoria=2&precioMax=2000&stock=true