POST http://localhost:3000/api/logistica/estado_pedido/
Content-Type: application/json

{
  "idPedido": 1,
  "idNuevoEstado": 4,
  "idUsuarioLogistica": 2
}

###
GET http://localhost:3000/api/logistica/estado_pedido/1