POST http://localhost:3000/api/logistica/estado_envio/
Content-Type: application/json

{
  "idPedido": 1,
  "idNuevoEstado": 3,
  "idUsuarioLogistica": 3
}

###
GET http://localhost:3000/api/logistica/estado_envio/1