-- Resetear la base de datos
-- Elimina todas las tablas y relaciones, y luego las vuelve a crear desde cero.
DROP SCHEMA public CASCADE;
-- Crea el esquema público nuevamente
CREATE SCHEMA public;


-- Producto
CREATE TABLE "Producto" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "nombre" VARCHAR(255) NOT NULL,
    "descripcion" TEXT NOT NULL,
    "precio" DECIMAL(10, 2) NOT NULL,
    "id_color" INT NOT NULL,
    "id_genero" INT NOT NULL,
    "id_subcategoria" INT NOT NULL,
    "id_marca" INT NOT NULL,
    "activo" BOOLEAN NOT NULL DEFAULT TRUE
);

-- Tallas
CREATE TABLE "Talla" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "nombre" VARCHAR(50) NOT NULL,
    "id_categoria" INT NOT NULL
);

-- StockPorTallas
CREATE TABLE "StockPorTallas" (
    "id_producto" INT NOT NULL,
    "id_talla" INT NOT NULL,
    "stock" INT NOT NULL check (stock >= 0),
    PRIMARY KEY ("id_producto", "id_talla")
);

-- Color
CREATE TABLE "Color" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "nombre" VARCHAR(50) NOT NULL
);

-- Genero
CREATE TABLE "Genero" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "nombre" VARCHAR(50) NOT NULL
);

-- Categoria
CREATE TABLE "Categoria" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "nombre" VARCHAR(50) NOT NULL
);

-- Subcategoria
CREATE TABLE "Subcategoria" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "nombre" VARCHAR(50) NOT NULL,
    "id_categoria" INT NOT NULL
);

-- Marca
CREATE TABLE "Marca" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "nombre" VARCHAR(50) NOT NULL,
    "imagen_url" VARCHAR(255) NOT NULL,
    "activo" BOOLEAN NOT NULL DEFAULT TRUE
);

-- ImagenProducto
CREATE TABLE "ImagenProducto" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "id_producto" INT NOT NULL,
    "url" VARCHAR(255) NOT NULL
);

-- Usuario
CREATE TABLE "Usuario" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "id_rol" INT NOT NULL,
    "nombre" VARCHAR(255) NOT NULL,
    "apellidos" VARCHAR(255) NOT NULL,
    "correo" VARCHAR(255) NOT NULL UNIQUE,
    "contrasena" VARCHAR(255) NOT NULL,
    "telefono" VARCHAR(20) NOT NULL UNIQUE,
    "foto_perfil" VARCHAR(255) NULL DEFAULT NULL,
    "activo" BOOLEAN NOT NULL DEFAULT TRUE,
    "eliminado_en" timestamptz NULL DEFAULT NULL
);

-- Rol
CREATE TABLE "Rol" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "nombre" VARCHAR(50) NOT NULL
);

-- Pedido
CREATE TABLE "Pedido" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "id_usuario" INT NOT NULL,
    "total" DECIMAL(10, 2) NOT NULL check (total >= 0),
    "fecha" timestamptz DEFAULT now(),
    "id_estado_pedido" INT NOT NULL
);

-- EstadoPedido
CREATE TABLE "EstadoPedido" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "nombre" VARCHAR(50) NOT NULL,
    "descripcion" VARCHAR(255) NOT NULL
);

-- DetallePedido
CREATE TABLE "DetallePedido" (
    "id_pedido" INT NOT NULL,
    "id_producto" INT NOT NULL,
    "id_talla" INT NOT NULL,
    "cantidad" INT NOT NULL check (cantidad > 0),
    "precio_unitario" DECIMAL(10, 2) NOT NULL check (precio_unitario >= 0),
    PRIMARY KEY ("id_pedido", "id_producto", "id_talla")
);

-- Pago
CREATE TABLE "Pago" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "id_pedido" INT NOT NULL,
    "id_tipo_metodo" INT NOT NULL,
    "referencia" VARCHAR(255) NOT NULL,
    "total" DECIMAL(10, 2) NOT NULL check (total >= 0),
    "fecha" timestamptz DEFAULT now(),
    "id_estado_pago" INT NOT NULL
);

-- EstadoPago
CREATE TABLE "EstadoPago" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "nombre" VARCHAR(50) NOT NULL,
    "descripcion" VARCHAR(255) NOT NULL
);

-- TipoMetodoDePago
CREATE TABLE "TipoMetodoDePago" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "nombre" VARCHAR(50) NOT NULL,
    "descripcion" VARCHAR(255) NOT NULL
);

-- MetodoDePago
CREATE TABLE "MetodoDePago" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "id_usuario" INT NOT NULL,
    "id_tipo_metodo" INT NOT NULL,
    "numero_cuenta" VARCHAR(255) NOT NULL,
    "nombre_titular" VARCHAR(255) NOT NULL,
    "fecha_vencimiento" DATE NOT NULL,
    "banco" VARCHAR(255) NOT NULL,
    "correo" VARCHAR(255) NOT NULL,
    "id_proveedor" INT NOT NULL
);

-- ProveedorBancario
CREATE TABLE "ProveedorBancario" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "nombre" VARCHAR(255) NOT NULL,
    "url_logo" VARCHAR(255) NOT NULL
);

-- CarritoCompras
CREATE TABLE "CarritoCompras" (
    "id_usuario" INT NOT NULL,
    "id_producto" INT NOT NULL,
    "id_talla" INT NOT NULL,
    "cantidad" INT NOT NULL check (cantidad > 0),
    PRIMARY KEY ("id_usuario", "id_producto", "id_talla")
);

-- DireccionEnvio
CREATE TABLE "DireccionEnvio" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "id_usuario" INT NOT NULL,
    "estado" VARCHAR(255) NOT NULL,
    "ciudad" VARCHAR(255) NOT NULL,
    "codigo_postal" VARCHAR(20) NOT NULL,
    "calle" VARCHAR(255) NOT NULL,
    "numero_exterior" VARCHAR(20) NOT NULL,
    "numero_interior" VARCHAR(20) NULL,
    "colonia" VARCHAR(255) NOT NULL,
    "eliminado_en" timestamptz NULL DEFAULT NULL
);

-- ListaDeseos
CREATE TABLE "ListaDeseos" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "id_usuario" INT NOT NULL
);

-- DetalleListaDeseos
CREATE TABLE "DetalleDeseos" (
    "id_lista_deseos" INT NOT NULL,
    "id_producto" INT NOT NULL,
    PRIMARY KEY ("id_lista_deseos", "id_producto")
);

-- Envio
CREATE TABLE "Envio" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "id_pedido" INT NOT NULL,
    "id_direccion" INT NOT NULL,
    "numero_guia" VARCHAR(255) NOT NULL,
    "fecha_envio" timestamptz DEFAULT now(),
    "fecha_entrega_estimada" timestamptz NOT NULL,
    "id_estado_envio" INT NOT NULL
);

-- EstadoEnvio
CREATE TABLE "EstadoEnvio" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "nombre" VARCHAR(50) NOT NULL,
    "descripcion" VARCHAR(255) NOT NULL
);

-- HistorialEstadoPedido
CREATE TABLE "HistorialEstadoPedido" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "id_pedido" INT NOT NULL,
    "id_estado_pedido" INT NOT NULL,
    "fecha" timestamptz DEFAULT now(),
    "id_usuario" INT NOT NULL
);


-- Relaciones entre tablas

-- Productos, Stock, Categorias, Subcategorias, Marcas, Colores, Generos
ALTER TABLE "Producto"
ADD FOREIGN KEY ("id_color") REFERENCES "Color"("id"),
ADD FOREIGN KEY ("id_genero") REFERENCES "Genero"("id"),
ADD FOREIGN KEY ("id_subcategoria") REFERENCES "Subcategoria"("id"),
ADD FOREIGN KEY ("id_marca") REFERENCES "Marca"("id");

ALTER TABLE "StockPorTallas"
ADD FOREIGN KEY ("id_producto") REFERENCES "Producto"("id"),
ADD FOREIGN KEY ("id_talla") REFERENCES "Talla"("id");

ALTER TABLE "Talla" ADD FOREIGN KEY ("id_categoria") REFERENCES "Categoria"("id");

ALTER TABLE "Subcategoria" ADD FOREIGN KEY ("id_categoria") REFERENCES "Categoria"("id");

ALTER TABLE "ImagenProducto" ADD FOREIGN KEY ("id_producto") REFERENCES "Producto"("id")
ON DELETE CASCADE;

-- Usuarios, Roles, Pedido, carrito, direcciones, metodos de pago
ALTER TABLE "Usuario" ADD FOREIGN KEY ("id_rol") REFERENCES "Rol"("id");

ALTER TABLE "Pedido" ADD FOREIGN KEY ("id_usuario") REFERENCES "Usuario"("id"),
ADD FOREIGN KEY ("id_estado_pedido") REFERENCES "EstadoPedido"("id");

ALTER TABLE "DetallePedido" ADD FOREIGN KEY ("id_pedido") REFERENCES "Pedido"("id"),
ADD FOREIGN KEY ("id_producto") REFERENCES "Producto"("id"),
ADD FOREIGN KEY ("id_talla") REFERENCES "Talla"("id");

ALTER TABLE "Pago" ADD FOREIGN KEY ("id_pedido") REFERENCES "Pedido"("id"),
ADD FOREIGN KEY ("id_tipo_metodo") REFERENCES "TipoMetodoDePago"("id"),
ADD FOREIGN KEY ("id_estado_pago") REFERENCES "EstadoPago"("id");

ALTER TABLE "MetodoDePago" ADD FOREIGN KEY ("id_usuario") REFERENCES "Usuario"("id"),
ADD FOREIGN KEY ("id_tipo_metodo") REFERENCES "TipoMetodoDePago"("id"),
ADD FOREIGN KEY ("id_proveedor") REFERENCES "ProveedorBancario"("id");

ALTER TABLE "CarritoCompras" ADD FOREIGN KEY ("id_usuario") REFERENCES "Usuario"("id"),
ADD FOREIGN KEY ("id_producto") REFERENCES "Producto"("id"),
ADD FOREIGN KEY ("id_talla") REFERENCES "Talla"("id");

ALTER TABLE "DireccionEnvio" ADD FOREIGN KEY ("id_usuario") REFERENCES "Usuario"("id");

ALTER TABLE "ListaDeseos" ADD FOREIGN KEY ("id_usuario") REFERENCES "Usuario"("id");

ALTER TABLE "DetalleDeseos" ADD FOREIGN KEY ("id_lista_deseos") REFERENCES "ListaDeseos"("id"),
ADD FOREIGN KEY ("id_producto") REFERENCES "Producto"("id");


-- Envio e historial de estados
ALTER TABLE "Envio" ADD FOREIGN KEY ("id_pedido") REFERENCES "Pedido"("id"),
ADD FOREIGN KEY ("id_direccion") REFERENCES "DireccionEnvio"("id"),
ADD FOREIGN KEY ("id_estado_envio") REFERENCES "EstadoEnvio"("id");

ALTER TABLE "HistorialEstadoPedido" ADD FOREIGN KEY ("id_pedido") REFERENCES "Pedido"("id"),
ADD FOREIGN KEY ("id_estado_pedido") REFERENCES "EstadoPedido"("id"),
ADD FOREIGN KEY ("id_usuario") REFERENCES "Usuario"("id");

ALTER TABLE "DetallePedido"
ADD FOREIGN KEY ("id_producto","id_talla")
REFERENCES "StockPorTallas"("id_producto","id_talla");

CREATE INDEX idx_historial_pedido
ON "HistorialEstadoPedido"(id_pedido);

CREATE INDEX idx_envio_pedido
ON "Envio"(id_pedido);

CREATE INDEX idx_pedido_usuario
ON "Pedido"(id_usuario);

CREATE INDEX idx_producto_marca ON "Producto"(id_marca);
CREATE INDEX idx_producto_genero ON "Producto"(id_genero);
CREATE INDEX idx_producto_color ON "Producto"(id_color);
CREATE INDEX idx_stock_producto ON "StockPorTallas"(id_producto);
CREATE INDEX idx_producto_filtros ON "Producto"(id_subcategoria, id_marca, id_genero);
CREATE INDEX idx_producto_activo ON "Producto"(id_subcategoria) WHERE activo = TRUE;
CREATE INDEX idx_stock_talla ON "StockPorTallas"(id_talla);

CREATE INDEX idx_stock_disponible
ON "StockPorTallas"(id_producto)
WHERE stock > 0;

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE INDEX idx_producto_nombre_trgm
ON "Producto"
USING gin (nombre gin_trgm_ops);

ALTER TABLE "Color" ADD CONSTRAINT color_nombre_unique UNIQUE (nombre);
ALTER TABLE "Genero" ADD CONSTRAINT genero_nombre_unique UNIQUE (nombre);
ALTER TABLE "Categoria" ADD CONSTRAINT categoria_nombre_unique UNIQUE (nombre);
ALTER TABLE "Marca" ADD CONSTRAINT marca_nombre_unique UNIQUE (nombre);
ALTER TABLE "Rol" ADD CONSTRAINT rol_nombre_unique UNIQUE (nombre);
ALTER TABLE "EstadoPedido" ADD CONSTRAINT estadopedido_nombre_unique UNIQUE (nombre);
ALTER TABLE "EstadoPago" ADD CONSTRAINT estadopago_nombre_unique UNIQUE (nombre);
ALTER TABLE "EstadoEnvio" ADD CONSTRAINT estadoenvio_nombre_unique UNIQUE (nombre);