//***********/
//* Nombre del equipo: Equipo 1 */
//* Autor de la clase: Cervantes Rosales Abdiel */
//* Fecha: 06/02/2026 */
//**********/

### REGISTRO CLIENTE
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "nombre": "pedro",
  "apellidos": "Perez",
  "correo": "pedro@test.com",
  "contrasena": "123456",
  "telefono": "9559876541"
}

###

### LOGIN CLIENTE
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "correo": "juan@test.com",
  "contrasena": "123456"
}

###


@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiY29ycmVvIjoianVhbkB0ZXN0LmNvbSIsInJvbCI6MiwiaWF0IjoxNzczNDQ2MjEzLCJleHAiOjE3NzM0NTM0MTN9.45_ky8OoavKRGUW1-EkfKXAwPPoH4UsYl_qp_o0cu7Y

###
//***********/
//* Nombre del equipo: Equipo 1 */
//* Autor de la clase: Ramos Bello Jose Luis */
//* Fecha: 06/02/2026 */
//**********/
### PERFIL DEL CLIENTE
GET http://localhost:3000/api/cliente/perfil
Authorization: Bearer {{token}}

###

### MODIFICAR PERFIL (DATOS GENERALES)
PATCH http://localhost:3000/api/cliente
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nombre": "Checo",
  "apellidos": "Perez",
  "telefono": "1299999996",
  "foto_perfil": "default.png"
}

###

### CAMBIAR CONTRASEÑA
PATCH http://localhost:3000/api/cliente
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "contrasena_actual": "123456",
  "nueva_contrasena": "NuevaClave789!"
}

###

### CAMBIAR CORREO
PATCH http://localhost:3000/api/cliente
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "correo": "abdielcer@test.com"
}

###

### ELIMINAR CUENTA
DELETE http://localhost:3000/api/cliente
Authorization: Bearer {{token}}