#--------------------------------------------------
# Equipo #1
# Adrien Hernández Sánchez
# 06 de febrero de 2026
# Endpoint: Agregar producto al carrito de compras
#--------------------------------------------------
POST http://localhost:3000/api/carrito
Content-Type: application/json

{
  "id_usuario": 1,
  "id_producto": 120,
  "id_talla": 3,
  "cantidad": 2
}