#--------------------------------------------------
# Equipo #1
# Adrien Hernández Sánchez
# 06 de febrero de 2026
# Endpoint: Vaciar carrito de compras
#--------------------------------------------------
DELETE http://localhost:3000/api/carrito/drop/
Content-Type: application/json

{
  "id_usuario": 2
}