#--------------------------------------------------
# Equipo #1
# Adrien Hernández Sánchez
# 06 de febrero de 2026
# Endpoint: Aumentar cantidad de articulo
# en el carrito de compras
#--------------------------------------------------
PUT http://localhost:3000/api/carrito/
Content-Type: application/json

{
  "id_usuario": 1,
  "id_producto": 2,
  "id_talla": 8,
  "cantidad": 3,
  "flag": "decrease"
}