#--------------------------------------------------
# Equipo #1
# Adrien Hernández Sánchez
# 06 de febrero de 2026
# Endpoint: Eliminar producto del carrito de compras
#--------------------------------------------------
DELETE http://localhost:3000/api/carrito/
Content-Type: application/json

{
  "id_usuario": 1,
  "id_producto": 1,
  "id_talla": 7
}