#--------------------------------------------------
# Equipo #1
# Adrien Hernández Sánchez
# 06 de febrero de 2026
# Endpoint: Aumentar cantidad de articulo
# en el carrito de compras
#--------------------------------------------------
PUT http://localhost:3000/api/carrito/10
Content-Type: application/json

{
  "clienteId": 1,
  "cantidad": 5,
  "flag": "increase"
}