CREATE TABLE "Categoria" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "nombre" varchar(30) UNIQUE NOT NULL
);

CREATE TABLE "CategoriaProducto" (
  "id_producto" integer NOT NULL,
  "id_categoria" integer NOT NULL,
  PRIMARY KEY ("id_producto", "id_categoria")
);

CREATE TABLE "Producto" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "nombre" varchar(100) NOT NULL,
  "precio" decimal(10,2) NOT NULL CHECK (precio >= 0),
  "stock" integer NOT NULL CHECK (stock >= 0),
  "activo" bool NOT NULL DEFAULT true
);

CREATE TABLE "ImagenProducto" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_producto" integer NOT NULL,
  "url" varchar(255) NOT NULL
);

CREATE TABLE "Administrador" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "nombre" varchar(30) NOT NULL,
  "apellidos" varchar(100) NOT NULL,
  "correo" varchar(50) UNIQUE NOT NULL,
  "contrasena" varchar(255) NOT NULL,
  "telefono" varchar(20) UNIQUE NOT NULL,
  "foto_perfil" varchar(255) NOT NULL
);

CREATE TABLE "Cliente" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "nombre" varchar(30) NOT NULL,
  "apellidos" varchar(100) NOT NULL,
  "correo" varchar(50) UNIQUE NOT NULL,
  "contrasena" varchar(255) NOT NULL,
  "telefono" varchar(20) UNIQUE NOT NULL,
  "foto_perfil" varchar(255) NOT NULL
);

CREATE TABLE "Pedido" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "id_cliente" integer NOT NULL,
  "total" decimal(10,2) NOT NULL CHECK (total >= 0),
  "fecha" timestamptz NOT NULL DEFAULT now(),
  "id_estado" integer NOT NULL
);

CREATE TABLE "DetallePedido" (
  "id_pedido" integer NOT NULL,
  "id_producto" integer NOT NULL,
  "cantidad" integer NOT NULL,
  "precio_unitario" decimal(10,2) NOT NULL CHECK (precio_unitario >= 0),
  PRIMARY KEY ("id_pedido", "id_producto")
);

CREATE TABLE "MetodoDePago" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "id_cliente" integer NOT NULL,
  "id_tipo" integer NOT NULL,
  "numero_cuenta" varchar(30) NOT NULL,
  "activo" bool NOT NULL DEFAULT true
);

CREATE TABLE "TipoMetodoDePago" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "tipo" varchar(50) NOT NULL
);

CREATE TABLE "Pago" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_pedido" integer NOT NULL,
  "id_metodo" integer NOT NULL,
  "total" decimal(10,2) NOT NULL,
  "fecha" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE "CarritoCompras" (
  "id_cliente" integer NOT NULL,
  "id_producto" integer NOT NULL,
  "cantidad" integer NOT NULL CHECK (cantidad > 0),
  PRIMARY KEY ("id_cliente", "id_producto")
);

CREATE TABLE "DireccionEnvio" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "id_cliente" integer NOT NULL,
  "estado" varchar(100) NOT NULL,
  "ciudad" varchar(100) NOT NULL,
  "codigo_postal" varchar(100) NOT NULL,
  "calle" varchar(100) NOT NULL,
  "numero_interno" varchar(100) NOT NULL,
  "numero_externo" varchar(100) NOT NULL,
  "colonia" varchar(100) NOT NULL
);

CREATE TABLE "ListaDeseos" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "id_cliente" integer NOT NULL
);

CREATE TABLE "DetalleDeseos" (
  "id_lista_deseos" integer NOT NULL,
  "id_producto" integer NOT NULL,
  PRIMARY KEY ("id_lista_deseos", "id_producto")
);

CREATE TABLE "EstadoPedido" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(30) UNIQUE NOT NULL,
  "descripcion" varchar(100)
);


CREATE TABLE "Marca" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(50) UNIQUE NOT NULL,
  "imagen_url" varchar(255) NOT NULL,
  "activo" boolean NOT NULL DEFAULT true
);


ALTER TABLE "CategoriaProducto" ADD FOREIGN KEY ("id_categoria") REFERENCES "Categoria" ("id");

ALTER TABLE "CategoriaProducto" ADD FOREIGN KEY ("id_producto") REFERENCES "Producto" ("id");

ALTER TABLE "ImagenProducto" ADD FOREIGN KEY ("id_producto") REFERENCES "Producto" ("id");

ALTER TABLE "Pedido" ADD FOREIGN KEY ("id_cliente") REFERENCES "Cliente" ("id");

ALTER TABLE "DetallePedido" ADD FOREIGN KEY ("id_pedido") REFERENCES "Pedido" ("id");

ALTER TABLE "MetodoDePago" ADD FOREIGN KEY ("id_cliente") REFERENCES "Cliente" ("id");

ALTER TABLE "Pago" ADD FOREIGN KEY ("id_metodo") REFERENCES "MetodoDePago" ("id");

ALTER TABLE "Pago" ADD FOREIGN KEY ("id_pedido") REFERENCES "Pedido" ("id");

ALTER TABLE "MetodoDePago" ADD FOREIGN KEY ("id_tipo") REFERENCES "TipoMetodoDePago" ("id");

ALTER TABLE "CarritoCompras" ADD FOREIGN KEY ("id_cliente") REFERENCES "Cliente" ("id");

ALTER TABLE "DireccionEnvio" ADD FOREIGN KEY ("id_cliente") REFERENCES "Cliente" ("id");

ALTER TABLE "ListaDeseos" ADD FOREIGN KEY ("id_cliente") REFERENCES "Cliente" ("id");

ALTER TABLE "DetalleDeseos" ADD FOREIGN KEY ("id_lista_deseos") REFERENCES "ListaDeseos" ("id");

ALTER TABLE "DetalleDeseos" ADD FOREIGN KEY ("id_producto") REFERENCES "Producto" ("id");

ALTER TABLE "DetallePedido" ADD FOREIGN KEY ("id_producto") REFERENCES "Producto" ("id");

ALTER TABLE "Pedido" ADD FOREIGN KEY ("id_estado") REFERENCES "EstadoPedido" ("id");


ALTER TABLE "Producto"
ADD COLUMN "id_marca" integer,
ADD CONSTRAINT "Producto_id_marca_fkey"
FOREIGN KEY ("id_marca")
REFERENCES "Marca" ("id")
ON DELETE SET NULL;

CREATE INDEX idx_marca_nombre ON "Marca"(nombre);


CREATE INDEX idx_pedido_cliente ON "Pedido"(id_cliente);
CREATE INDEX idx_metodo_cliente ON "MetodoDePago"(id_cliente);
CREATE INDEX idx_imagen_producto ON "ImagenProducto"(id_producto);


ALTER TABLE "Cliente"
ADD COLUMN activo boolean NOT NULL DEFAULT true,
ADD COLUMN eliminado_en timestamptz;
