//***********/
//* Nombre del equipo: Equipo 1 */
//* Autor de la clase: Cervantes Rosales Abdiel */
//* Fecha: 26/02/2026 */
//**********/

### Detalle del pedido
GET http://localhost:3000/api/pedido/1


### Historial pedidos usuario
GET http://localhost:3000/api/pedido/cliente/1


### Obtener comprobante
GET http://localhost:3000/api/pedido/1/comprobante