POST  http://localhost:3000/api/metodosdepago/agregar
Content-Type: application/json

{
  "id_cliente": 1,
  "id_tipo": 1,
  "numero_cuenta": "4441021111111111",
  "nombre_titular": "Luis Diaz",
  "fecha_vencimiento": "2029-12-01",
  "banco": null,
  "correo": null,
  "proveedor": "VISA"
}