//***********/
//* Nombre del equipo: Equipo 1 */
//* Autor de la clase: Cervantes Rosales Abdiel */
//* Fecha: 06/02/2026 */
//**********/
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "nombre": "Luis Fernando",
  "apellidos": "Perez",
  "correo": "abdielcer@test.com",
  "contrasena": "123456",
  "telefono": "9589876543",
  "foto_perfil": "t.png"
}

### LOGIN
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "correo": "abdielcer@test.com",
  "contrasena": "NuevaClave789!"
}
//***********/
//* Nombre del equipo: Equipo 1 */
//* Autor de la clase: Ramos Bello Jose Luis */
//* Fecha: 06/02/2026 */
//**********/
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiY29ycmVvIjoiYWJkaWVsY2VyQHRlc3QuY29tIiwiaWF0IjoxNzcwNDM0MDU4LCJleHAiOjE3NzA0NDEyNTh9.eR3AcDRc4YYRD5v9aFaYVxlcNfjZ-2Yc5e03-Dl4e6Q

### Perfil del cliente
GET http://localhost:3000/api/cliente/perfil
Authorization: Bearer {{token}}

### Modificar perfil de cliente
PATCH http://localhost:3000/api/cliente
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nombre": "Checo",
  "apellidos": "Perez",
  "telefono": "1299999996",
  "foto_perfil": "default.png"
}
###

PATCH http://localhost:3000/api/cliente
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "contrasena_actual": "123456",
  "nueva_contrasena": "NuevaClave789!"
}

###
PATCH http://localhost:3000/api/cliente
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "correo": "abdielcer@test.com"   # correo de otro usuario
}


### Eliminar cuenta de cliente
DELETE http://localhost:3000/api/cliente
Authorization: Bearer {{token}}
